export const apiConstants = {
    SET_TOGGLE_FETCH: 'SET_TOGGLE_FETCH',
    SET_SNACKBAR: 'SET_SNACKBAR'
    /*
    FETCHING_START: 'FETCHING_START',
    FETCHING_END: 'FETCHING_END',

    SNACKBAR_SUCCESS: 'SNACKBAR_SUCCESS',
    SNACKBAR_CLEAR: 'SNACKBAR_CLEAR',

    SNACKBAR_FAILURE: 'SNACKBAR_FAILURE',
    SNACKBAR_FAILURE_CLEAR: 'SNACKBAR_FAILURE_CLEAR'
    */
}