export const SET_TOGGLE_FETCH = 'SET_TOGGLE_FETCH'
export const SET_SNACKBAR = 'SET_SNACKBAR'


export const SET_TODO_ITEMS = "SET_TODO_ITEMS";
export const ADD_TODO_ITEM = "ADD_TODO_ITEM";
export const UPDATE_TODO_ITEM = "UPDATE_TODO_ITEM";
export const REMOVE_TODO_ITEM = "REMOVE_TODO_ITEM";
export const SET_TODO_FILTER = "SET_TODO_FILTER";