export const todoConstants = {
    TODO_GETALL_REQUEST: 'TODO_GETALL_REQUEST',
    TODO_GETALL_SUCCESS: 'TODO_GETALL_SUCCESS',
    TODO_GETALL_FAILURE: 'TODO_GETALL_FAILURE',

    TODO_GET_REQUEST: 'TODO_GET_REQUEST',
    TODO_GET_SUCCESS: 'TODO_GET_SUCCESS',
    TODO_GET_FAILURE: 'TODO_GET_FAILURE',

    TODO_CREATE_REQUEST: 'TODO_CREATE_REQUEST',
    TODO_CREATE_SUCCESS: 'TODO_CREATE_SUCCESS',
    TODO_CREATE_FAILURE: 'TODO_CREATE_FAILURE',

    TODO_UPDATE_REQUEST: 'TODO_UPDATE_REQUEST',
    TODO_UPDATE_SUCCESS: 'TODO_UPDATE_SUCCESS',
    TODO_UPDATE_FAILURE: 'TODO_UPDATE_FAILURE',

    TODO_DELETE_REQUEST: 'TODO_DELETE_REQUEST',
    TODO_DELETE_SUCCESS: 'TODO_DELETE_SUCCESS',
    TODO_DELETE_FAILURE: 'TODO_DELETE_FAILURE',

    TODO_SETCOMPLETED_REQUEST: 'TODO_SETCOMPLETED_REQUEST',
    TODO_SETCOMPLETED_SUCCESS: 'TODO_SETCOMPLETED_SUCCESS',
    TODO_SETCOMPLETED_FAILURE: 'TODO_SETCOMPLETED_FAILURE'
}