export const todoConstants = {
    TODO_SET_ITEMS: 'TODO_SET_ITEMS',
    TODO_ADD_ITEM: 'TODO_ADD_ITEM',
    TODO_UPDATE_ITEM: 'TODO_UPDATE_ITEM',
    TODO_REMOVE_ITEM: 'TODO_REMOVE_ITEM',
    TODO_SET_FILTER: 'TODO_SET_FILTER'
}